name: Sync Upstream
on:
  schedule:
    - cron: '22 * * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with Upstream
        uses: ahmadnassri/action-upstream-sync@v2
        with:
          upstream_repository: consumet/consumet-api
          target_branch: master # or main
